#!/usr/bin/env bash

# -----------------------------------------------------
# Helper functions
# -----------------------------------------------------

function build_secrets {
  if [[ ! -f "$SECRETS/ca.crt" || ! -f "$SECRETS/ca.key" ]]; then
    make-ca redis -o "$SECRETS"
  fi
  make-cert redis "$REDIS_NODES $REDIS_FQDN_NODES" -o "$SECRETS" --ca-crt "$SECRETS/ca.crt" --ca-key "$SECRETS/ca.key"
  make-truststore redis "$SECRETS/ca.crt" -o "$SECRETS"
}

function check_python_env {
  local in_venv missing packages pkg

  in_venv=$(python3 -c 'import sys; print(int(hasattr(sys,"real_prefix") or sys.prefix!=getattr(sys,"base_prefix",sys.prefix)))')

  if [[ "$in_venv" -ne 1 ]]; then
    log_error "Python virtualenv not enabled."
    exit 1
  fi

  missing=()
  packages=(click redis dotenv)
  for pkg in "${packages[@]}"; do
    python3 -c "import $pkg" 2>/dev/null || missing+=("$pkg")
  done

  if (( ${#missing[@]} > 0 )); then
    log_error "Missing modules: ${missing[*]}"
    exit 1
  fi
}

# -----------------------------------------------------
# Stack functions
# -----------------------------------------------------

function stack_check_env {
  if [ ! -d "$CONFIGS" ] || [ ! -d "$SECRETS" ]; then
    echo "Configs or secrets directory are missing from '$ENVIRONMENT_BASE'."
    exit 1
  fi
}

function stack_discover {
  export REDIS_MASTER_NODE=$(first "$REDIS_FQDN_NODES")
  export REDIS_REPLICAS=$(count "$REDIS_NODES")
}

function stack_tools {
  local tool is_python
  
  tool="$STACK_PATH/tools/$1"
  shift

  if [[ ! -x "$tool" ]]; then
    log_error "$tool doesn't exist or isn't executable."
    exit 1
  fi

  head -n1 "$tool" | grep -q 'python'
  is_python=$?

  if [[ $is_python -eq 0 ]]; then
    check_python_env
  fi

  log_info "Running $tool with args: $@"
  "$tool" "$@"
}

function stack_env {
  echo
  echo "DOCKER IMAGE  = $REDIS_IMAGE"
  echo "REDIS NODES   = ($REDIS_REPLICAS)"
  list "$REDIS_NODES"
  echo
  echo "TLS PORT      = $REDIS_TLS_PORT"
  echo
}

function stack_deploy {
  build_secrets
  docker stack deploy --detach=true -c redis.yml "$STACK"

  # TODO: Replace with something more reliable... redis-cli ping?
  log_info "Waiting for stack to stabilise..."
  sleep 60
  log_info "Creating admin user..."
  stack_tools make-user admin $REDIS_NODES "atlas.$DOMAIN"
  log_info "Disabling default user..."
  stack_tools client ACL SETUSER default off
  stack_tools client "ACL SAVE"
}
