#!/usr/bin/env bash
#
# Reads config from $CONFIGS/acls and creates the
# specified users and ACLs.

source "$TOOLS_BIN/lib/logging.sh"

TOOLS="${STACK_PATH}/tools"

# -----------------------------------------------------
# Functions
# -----------------------------------------------------

function create_acls {
  local file user enabled hosts patterns acls fqdn_hosts

  for file in "$CONFIGS/acls/"*.yml "$CONFIGS/acls/"*.yaml; do
    [ -e "$file" ] || continue

    user=$(yq -r '.user' "$file")
    enabled=$(yq -r '.enabled' "$file")
    hosts=$(yq -r '.hosts[]' "$file")
    patterns=$(yq -r '.patterns' "$file")
    acls=$(yq -r '.acls' "$file")

    fqdn_hosts=""
    for host in $hosts; do
      fqdn_hosts+="$host $host.$DOMAIN "
    done

    log_info "Creating $user."
    # The default user doesn't need certs or a password
    if [ "$user" == "default" ]; then
      log_info "Skipping secret creation for default user ($user)."
      "$TOOLS/client" "ACL SETUSER $user $enabled $patterns $acls"
    else
      if [ ! -f "$SECRETS/$user-keystore.jks" ]; then
        log_info "Creating new certs and keystore..."
        "$TOOLS/make-user" "$user" "$fqdn_hosts"
      fi

      source "$SECRETS/$user-secrets.env"

      "$TOOLS/client" "ACL SETUSER $user >$REDIS_ACL_PASSWORD $enabled $patterns $acls"
    fi
  done
}

# -----------------------------------------------------
# Main
# -----------------------------------------------------

log_info "Creating users and ACLs"
create_acls

"$TOOLS/client" "ACL SAVE"
