#!/usr/bin/env bash
#
# Tactical script for clearing out keys with a specific pattern.
# Don't use for large amounts of keys...
#
# Usage: delete-pattern <pattern>

source "$TOOLS_BIN/lib/logging.sh"

if [ ! -f "$SECRETS/admin-secrets.env" ]; then
  log_error "Admin credentials aren't defined at '$SECRETS/admin-secrets.env'."
  exit 1
fi

source "$SECRETS/admin-secrets.env"

REDIS_ACL_PASSWORD=$(echo -e "$REDIS_ACL_PASSWORD" | tr -d '\r')
PATTERN="$1"

KEYS=$(docker -H unix:///var/run/docker.sock run -it --rm -v "$SECRETS:/etc/redis/secrets" \
    "$REDIS_IMAGE" redis-cli --no-auth-warning --user admin --pass "$REDIS_ACL_PASSWORD" \
    --tls -h "$REDIS_MASTER_NODE" -p "$REDIS_TLS_PORT" --cacert /etc/redis/secrets/ca.crt \
    --cert /etc/redis/secrets/redis.crt --key /etc/redis/secrets/redis.key \
    --scan --pattern $PATTERN)

# This is extremely inefficent but I can't get xargs to work properly
# and this is more of a tactical fix script...
for KEY in $KEYS; do
  docker -H unix:///var/run/docker.sock run -it --rm -v "$SECRETS:/etc/redis/secrets" \
      "$REDIS_IMAGE" redis-cli --no-auth-warning --user admin --pass "$REDIS_ACL_PASSWORD" \
      --tls -h "$REDIS_MASTER_NODE" -p "$REDIS_TLS_PORT" --cacert /etc/redis/secrets/ca.crt \
      --cert /etc/redis/secrets/redis.crt --key /etc/redis/secrets/redis.key DEL $KEY
done
