#!/usr/bin/env bash
#
# Creates the certs, keystore, and Redis secrets for a user.
# DOES NOT CREATE THE ACLS!
#
# Usage: make-user <user> <hostname1> [hostname2 ...]

USER="$1"
shift
HOSTS="$*"

make-keystore "$USER" "$HOSTS" -o "$SECRETS"

if [ ! -f "$SECRETS/$USER-secrets.env" ]; then
    REDIS_ACL_PASSWORD=$(openssl rand -base64 48 | tr -dc 'A-Za-z0-9' | head -c 32)
    echo "export REDIS_ACL_PASSWORD=$REDIS_ACL_PASSWORD" > "$SECRETS/$USER-secrets.env"
fi
